### ISSUE TITLE
Yeo 17

### ISSUE THREAD

**Issue by nooshinjava** [ggseg/ggsegYeo2011#2]
Hi, Control C and Control A are labelled differently in the paper (Yeo et. al, 2011)

**Comment by drmowinckels** [comment]
Do you have more information about this? 
We've used the released label files from the Yeo lab, so if they are wrong, it means the Yeo lab's files we've used are also wrong.

**Comment by nooshinjava** [comment]
Hello,

Here is the code:

colSidem <-  c("#f44336", "#e81e63", "#9c27b0", "#673ab7", "#3f51b5",
"#2196f3", "#03a9f4",
"#00bcd4", "#009688", "#4caf50", "#8bc34a", "#cddc39", "#ffeb3b",
"#ffc107", "#ff9800", "#ff5722", "#8e83b5", "#000000")


Ps0 = ggplot() + geom_brain(atlas = yeo17,  position = position_brain(hemi
~ side))+ theme_void()  +
  theme(legend.position = "bottom",
        legend.text = element_text(size = 10)) +
  guides(fill = guide_legend(ncol = 5)) +
   scale_fill_manual(values = colSidem)

and I have attached the figure by R and the famous  Yeo-17 networks figure (
https://github.com/ThomasYeoLab/CBIG/tree/master/stable_projects/brain_parcellation/Schaefer2018_LocalGlobal
).
The control A region is different in these two figure.


Best regards,

Nooshin Javaheripour

 -------------------------------------------------------

Department of Psychiatry and Psychotherapy,
Jena University Hospital,
Philosophenweg 3,
07743 Jena, Germany

***@***.***
